export const ADD_TASK_BLOCK = "ADD_TASK_BLOCK";
export const ADD_TASK = "ADD_TASK";
export const SET_PARENT_CURRENT_ID = "SET_PARENT_CURRENT_ID";
export const EDIT_TASK = "EDIT_TASK";
export const SET_EDIT_TASK_ID = "SET_EDIT_TASK_ID";

export const SET_TARGET_DROP = "SET_TARGET_DROP";
export const SET_TARGET_DRAG = "SET_TARGET_DRAG";
export const EDIT_PARENT_TASK_BLOCK = "EDIT_PARENT_TASK_BLOCK";